[run]
init_cmds = [
  ["go", "build","-o", "./bin/resistor", "./pkg/"],
	["./bin/resitor"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR/pkg",
]
watch_exts = [".go", ".toml"]
build_delay = 1500
cmds = [
  ["go", "build", "-o", "./bin/resistor", "./pkg/"],
	["./bin/resistor"]
]
